# -*- coding: utf-8 -*-
"""Foundations_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kxsZZeM0BdnsM6K7QJkv7s8fYHkEqyG
"""

from bs4 import BeautifulSoup as bs
import requests
url = "https://web.archive.org/web/20230902185655/https://en.everybodywiki.com/100_Most_Highly-Ranked_Films"

get_url = requests.get(url).text
soup = bs(get_url, "html.parser")
table = soup.find_all("table", class_="wikitable")[0]
headers = []
rank = []
year = []
film = []
for index,row in enumerate(table.find_all("tr")):
  if index==0:
    for el in row.find_all("th")[:3]:
      headers.append(el.text.strip("th"))
  else:
        # Get all td elements in the row
        cells = row.find_all("td")[:3]
        # Check if there are enough cells to unpack
        for index,vals in enumerate(cells):
          if index==0:
            rank.append(vals.text.strip())
          elif index==1:
            film.append(vals.text.strip())
          else:
            year.append(vals.text.strip())

rows_list = {k:[] for k in headers}
for i in range(len(rank)):
  rows_list["Average Rank"].append(rank[i])
  rows_list["Film"].append(film[i])
  rows_list["Year"].append(year[i])

import pandas as pd
import sqlite3
db_name = "Movies.db"
sql_connection = sqlite3.connect(db_name)
df = pd.DataFrame(rows_list,columns=headers)
df.to_csv("top_50_films.csv",index=False)
df.to_sql("database.db",sql_connection,if_exists="replace",index=False)
sql_connection.close()